import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('id'), Locale('en')];

  static const List<LocalizationsDelegate<dynamic>> localizationsDelegates = [
    _AppLocalizationsDelegate(),
    GlobalMaterialLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
  ];

  static AppLocalizations of(BuildContext context) {
    final localization = Localizations.of<AppLocalizations>(
      context,
      AppLocalizations,
    );
    if (localization == null) {
      throw StateError('AppLocalizations tidak tersedia.');
    }
    return localization;
  }

  static final Map<String, Map<String, String>> _values = {
    'id': {
      'profile': 'Profil',
      'app_preferences': 'Preferensi Aplikasi',
      'language': 'Bahasa',
      'theme': 'Tema',
      'currency': 'Mata Uang',
      'billing_cycle_start': 'Awal Siklus Bulanan',
      'tx_time_input': 'Input Tanggal',
      'tx_time_with_time': 'Tanggal + Jam',
      'tx_time_date_only': 'Tanggal saja',
      'date_label': 'Tanggal',
      'notifications': 'Notifikasi',
      'recurring_bills': 'Tagihan Rutin',
      'recurring_bills_desc':
          'Pengingat tagihan, tidak membuat transaksi otomatis',
      'getting_started_title': 'Mulai dari sini',
      'getting_started_desc':
          'Tambahkan transaksi dan tagihan pertama agar dashboard terisi otomatis.',
      'add_first_transaction': 'Tambah Transaksi',
      'add_first_bill': 'Tambah Tagihan',
      'onboarding_step_tx': 'Tambah transaksi pertama',
      'onboarding_step_bill': 'Tambah tagihan rutin pertama',
      'onboarding_step_streak': 'Catat 3 hari beruntun',
      'habit_loop_title': 'Konsistensi Harian',
      'weekly_challenge': 'Tantangan Mingguan',
      'challenge_complete': 'Tantangan selesai. Pertahankan ritme!',
      'challenge_progress_hint': 'Lanjut catat hari ini untuk naik level.',
      'day_short': 'hari',
      'budget_limit': 'Batas Anggaran',
      'budget_limit_desc': 'Alert saat hampir melewati budget',
      'budget_settings': 'Atur Batas Anggaran',
      'daily_summary': 'Ringkasan Harian',
      'daily_summary_desc': 'Laporan cashflow harian',
      'summary_time': 'Waktu Ringkasan',
      'security_sync': 'Keamanan & Sinkronisasi',
      'security_backup': 'Keamanan & Backup',
      'backup_restore': 'Backup & Restore',
      'backup_restore_desc': 'Kelola cadangan dan pemulihan data',
      'security_pin': 'PIN Keamanan',
      'security_pin_desc': 'Fallback saat biometrik gagal',
      'create_pin': 'Buat PIN',
      'change_pin': 'Ubah PIN',
      'confirm_pin': 'Konfirmasi PIN',
      'pin_4_6_digits': 'Gunakan 4-6 digit angka',
      'remove_pin': 'Hapus PIN',
      'remove_pin_desc': 'Nonaktifkan fallback PIN',
      'pin_saved': 'PIN keamanan tersimpan',
      'pin_removed': 'PIN keamanan dihapus',
      'pin_not_match': 'PIN dan konfirmasi tidak sama',
      'backup_status_title': 'Status Backup',
      'backup_last': 'Terakhir backup',
      'backup_never': 'Belum pernah backup',
      'backup_now': 'Backup sekarang',
      'data_reports': 'Data & Laporan',
      'period': 'Periode',
      'all_time': 'Semua waktu',
      'legal_privacy': 'Legal & Privasi',
      'legal_privacy_desc': 'Privacy policy, terms, data safety',
      'help': 'Bantuan',
      'logout': 'Tutup Profil',
      'home_greeting': 'Halo',
      'financial_dashboard': 'Dashboard Finansial',
      'total_balance': 'Total Saldo Bersih',
      'income_this_cycle': 'Pemasukan',
      'expense_this_cycle': 'Pengeluaran',
      'monthly_bills': 'Tagihan Rutin Bulanan',
      'item_count': 'item',
      'no_bills': 'Belum ada tagihan rutin',
      'due_today': 'Hari ini',
      'due_in_days': 'hari lagi',
      'due_date': 'Jatuh tempo tgl',
      'more_bills': 'tagihan lainnya',
      'financial_analytics': 'Analitik Keuangan',
      'days_30': '30 Hari',
      'saving_rate': 'Saving Rate',
      'burn_rate': 'Burn Rate',
      'runway': 'Runway',
      'trend_7_days': 'Tren 7 Hari',
      'top_categories': 'Top Kategori',
      'culinary_up': 'Kuliner naik 24%',
      'wallet_title': 'Dompet Saya',
      'active_balance': 'Saldo Aktif',
      'monthly_cashflow': 'Cashflow Bulanan',
      'income': 'Uang Masuk',
      'expense': 'Uang Keluar',
      'difference': 'Selisih',
      'income_expense_history': 'Riwayat Uang Masuk/Keluar',
      'finance_analytics': 'Analitik Keuangan',
      'share_soon': 'Fitur bagikan laporan segera tersedia',
      'this_week': 'Minggu Ini',
      'this_month': 'Bulan Ini',
      'this_year': 'Tahun Ini',
      'custom': 'Kustom',
      'total_expense': 'Total Pengeluaran',
      'total_income': 'Total Pemasukan',
      'net_balance': 'Saldo Bersih',
      'avg_daily': 'Rata-rata / Hari',
      'expense_trend': 'TREN PENGELUARAN',
      'expense_composition': 'KOMPOSISI PENGELUARAN',
      'out': 'Keluar',
      'in': 'Masuk',
      'days_7': '7 Hari',
      'largest_category': 'Kategori terbesar: Makanan & Minuman (45%).',
      'transaction_detail': 'Detail Transaksi',
      'history_soon':
          'Riwayat transaksi akan ditampilkan di pembaruan berikutnya',
      'expense_tab': 'Pengeluaran',
      'income_tab': 'Pemasukan',
      'detail_info': 'DETAIL INFORMASI',
      'fund_source': 'Sumber Dana',
      'category': 'Kategori',
      'date_time': 'Tanggal & Waktu',
      'add_note': 'Tambahkan catatan...',
      'payment_proof': 'Bukti Transaksi',
      'camera': 'Kamera',
      'gallery': 'Galeri',
      'cleared': 'Sudah Lunas',
      'add_recurring_bill': 'Tambah Tagihan Rutin',
      'save_data': 'SIMPAN DATA',
      'invalid_amount': 'Nominal transaksi belum valid',
      'saved_success': 'Transaksi berhasil disimpan',
      'monthly_recurring_bill': 'Tagihan Rutin Bulanan',
      'bill_name': 'Nama Tagihan',
      'bill_name_hint': 'Contoh: Bayar Air',
      'amount': 'Nominal',
      'amount_hint': 'Contoh: 250000',
      'due_day': 'Tanggal Jatuh Tempo',
      'due_day_hint': '1 - 31',
      'cancel': 'Batal',
      'save': 'Simpan',
      'bill_added': 'Tagihan rutin ditambahkan ke dashboard',
      'bill_updated': 'Tagihan rutin berhasil diperbarui',
      'bill_deleted': 'Tagihan rutin berhasil dihapus',
      'edit': 'Edit',
      'delete': 'Hapus',
      'manage_recurring_bills': 'Kelola Tagihan Rutin',
      'manage_recurring_bills_desc':
          'Pengingat tagihan bulanan, bukan transaksi otomatis',
      'edit_recurring_bill': 'Edit Tagihan Rutin',
      'delete_recurring_bill': 'Hapus Tagihan Rutin',
      'delete_recurring_bill_confirm': 'Yakin ingin menghapus tagihan',
      'invalid_recurring_bill': 'Data tagihan rutin belum valid',
      'remove_seed_bills': 'Hapus Data Contoh',
      'seed_bills_removed': 'Data contoh tagihan berhasil dihapus',
      'seed_bills_not_found': 'Data contoh tidak ditemukan',
      'master_data_center': 'Pusat Data Master',
      'master_data_center_desc': 'Kelola dompet dan kategori',
      'manage_wallets': 'Kelola Dompet',
      'manage_wallets_desc': 'Tambah atau hapus dompet',
      'rename_wallet': 'Ubah Nama Dompet',
      'rename_category': 'Ubah Nama Kategori',
      'wallet_name_hint': 'Contoh: tabungan_bri',
      'category_name_hint': 'Contoh: freelance',
      'add': 'Tambah',
      'budget_scope': 'Cakupan Anggaran',
      'budget_scope_all': 'Semua Pengeluaran',
      'budget_scope_category': 'Per Kategori',
      'budget_scope_wallet': 'Per Dompet',
      'budget_period_days': 'Periode',
      'budget_calendar_month': 'Periode anggaran: bulan kalender berjalan',
      'select_language': 'Pilih Bahasa',
      'select_theme': 'Pilih Tema',
      'select_currency': 'Pilih Mata Uang',
      'theme_system': 'Otomatis',
      'theme_light': 'Terang',
      'theme_dark': 'Gelap',
      'recurring_bills_on': 'Tagihan Rutin Aktif',
      'recurring_bills_on_desc': 'Pengingat tagihan rutin sudah diaktifkan.',
      'budget_on': 'Batas Anggaran Aktif',
      'budget_on_desc': 'Notifikasi anggaran sudah diaktifkan.',
      'budget_alert': 'Alert',
      'daily_summary_body': 'Catat pemasukan dan pengeluaran hari ini.',
      'daily_summary_on': 'Ringkasan Harian Aktif',
      'daily_summary_on_desc': 'Notifikasi ringkasan harian sudah diaktifkan.',
      'budget_saved': 'Batas Anggaran Disimpan',
      'monthly_limit': 'Limit Bulanan',
      'alert_when': 'Peringatan Saat',
      'alert_70': '70% dari limit',
      'alert_80': '80% dari limit',
      'alert_90': '90% dari limit',
      'alert_100': '100% dari limit',
      'transactions': 'Transaksi',
      'categories': 'Kategori',
      'accounts': 'Akun',
      'export_reports': 'Export Laporan',
      'export_reports_desc': 'CSV lengkap / PDF ringkasan',
      'export_reports_action': 'Export laporan dimulai',
      'manage_categories': 'Kelola Kategori',
      'manage_categories_desc':
          'Kategori dipisah untuk pemasukan dan pengeluaran',
      'manage_expense_categories': 'Kategori Pengeluaran',
      'manage_expense_categories_desc':
          'Muncul saat transaksi bertipe pengeluaran',
      'manage_income_categories': 'Kategori Pemasukan',
      'manage_income_categories_desc':
          'Muncul saat transaksi bertipe pemasukan',
      'expense_category_scope': 'Kategori ini khusus untuk pengeluaran',
      'income_category_scope': 'Kategori ini khusus untuk pemasukan',
      'opening_balance': 'Saldo Awal',
      'opening_balance_desc': 'Saldo dompet sebelum mulai mencatat transaksi.',
      'sample_data': 'Contoh',
      'sample_data_desc': 'Data contoh, aman dihapus saat data asli siap.',
      'manage_categories_action': 'Kelola kategori dibuka',
      'manual_sync': 'Sinkronisasi Manual',
      'manual_sync_desc': 'Terakhir: hari ini 14:03',
      'manual_sync_action': 'Sinkronisasi manual dijalankan',
      'help_center': 'Pusat Bantuan',
      'help_center_desc': 'Panduan fitur & FAQ',
      'help_center_action': 'Pusat bantuan dibuka',
      'contact_support': 'Hubungi Support',
      'contact_support_desc': 'Balasan < 1x24 jam',
      'contact_support_action': 'Form support dibuka',
      'about_app': 'Tentang Aplikasi',
      'about_app_desc': 'Versi 1.0.0+1',
      'about_app_action': 'Informasi aplikasi ditampilkan',
      'biometric_lock': 'Kunci Biometrik',
      'biometric_lock_desc': 'Akses aplikasi dengan sidik jari/wajah',
      'cloud_sync': 'Sinkronisasi Cloud',
      'cloud_sync_desc':
          'Belum aktif. Gunakan backup lokal untuk pindah perangkat',
      'auto_backup': 'Backup Otomatis',
      'auto_backup_desc':
          'Backup lokal terenkripsi mingguan, bukan sinkron cloud',
      'per_day': 'hari',
      'runway_value': '5.9 bln',
      'category_food': 'Kuliner',
      'category_transport': 'Transport',
      'category_bills': 'Tagihan',
      'category_food_drink': 'Makanan & Minuman',
      'category_monthly_shopping': 'Belanja Bulanan',
      'category_shopping': 'Belanja',
      'category_entertainment': 'Hiburan',
      'category_health': 'Kesehatan',
      'category_education': 'Pendidikan',
      'category_others': 'Lain-lain',
      'category_salary': 'Gaji',
      'category_freelance': 'Freelance',
      'category_bonus': 'Bonus',
      'category_business': 'Usaha',
      'category_investment': 'Investasi',
      'category_gift': 'Hadiah',
      'wallet_cash': 'Tunai',
      'wallet_bank': 'Bank',
      'wallet_ewallet': 'E-Wallet',
      'wallet_card': 'Kartu',
      'salary_in': 'Gaji Masuk',
      'company_to_bank': 'Perusahaan -> BCA',
      'pay_water': 'Bayar Air (PDAM)',
      'monthly_shopping': 'Belanja Bulanan',
      'credit_card': 'Kartu Kredit',
      'cash': 'Tunai',
      'date_mar_1_2026': '1 Mar 2026',
      'date_mar_5_2026': '5 Mar 2026',
      'date_mar_7_2026': '7 Mar 2026',
      'trx_52': '52 trx',
      'trx_18': '18 trx',
      'trx_14': '14 trx',
      'trx_7': '7 trx',
      'logout_action': 'Proses keluar akun disiapkan',
      'no_data': 'Belum ada data',
      'transactions_count': 'transaksi',
      'see_all_breakdown': 'Lihat Semua Kategori',
      'expense_by_category': 'Pengeluaran per Kategori',
      'total': 'Total',
      'largest_category_none': 'Belum ada kategori dominan',
      'month_short': 'bln',
      'top_categories_info':
          '3 kategori dengan pengeluaran terbesar pada siklus berjalan.',
      'no_tx_short': '0',
      'saving_rate_info':
          'Persentase pemasukan yang berhasil disimpan setelah dikurangi pengeluaran siklus ini.',
      'burn_rate_info':
          'Rata-rata pengeluaran per hari pada siklus berjalan. Semakin tinggi, uang lebih cepat habis.',
      'runway_info':
          'Perkiraan berapa lama saldo saat ini bisa bertahan jika pola pengeluaran sekarang tidak berubah.',
      'saving_rate_example':
          'Contoh: Masuk 5 jt, keluar 3 jt, saving rate = 40%',
      'burn_rate_example': 'Contoh: Keluar 3 jt dalam 30 hari = 100 rb/hari',
      'runway_example':
          'Contoh: Saldo 10 jt, burn rate 100 rb/hari = sekitar 100 hari',
      'search_hint': 'Cari transaksi...',
      'search_empty': 'Transaksi tidak ditemukan',
      'notif_center_title': 'Pusat Notifikasi',
      'notif_center_empty': 'Belum ada notifikasi',
      'notif_bill_due_title': 'Tagihan mendekati jatuh tempo',
      'notif_upcoming': 'Segera',
      'notif_expense_added': 'Pengeluaran tercatat',
      'notif_income_added': 'Pemasukan tercatat',
      'notif_just_now': 'Baru saja',
      'monthly_close_title': 'Tutup Bulan',
      'monthly_close_export_pdf': 'Export PDF',
      'monthly_close_exported': 'PDF tersimpan',
      'recent_activity_title': 'Aktivitas Terbaru',
      'tap_to_edit': 'Tap untuk edit',
      'savings_goal_title': 'Target Tabungan',
      'set_goal': 'Atur',
      'savings_goal_empty': 'Belum ada target tabungan',
      'goal_reached': 'Target tercapai',
      'goal_progress': '{value}% tercapai',
      'goal_name': 'Nama Target',
      'goal_target_amount': 'Target Nominal',
      'delete_goal': 'Hapus Target',
      'export_failed': 'Export gagal',
      'recurring_tx_title': 'Template Transaksi Otomatis',
      'recurring_tx_manage': 'Template transaksi',
      'recurring_tx_add': 'Tambah Template',
      'recurring_tx_edit': 'Edit Template',
      'recurring_tx_empty': 'Belum ada template transaksi rutin',
      'recurring_tx_type': 'Tipe',
      'recurring_tx_income': 'Pemasukan',
      'recurring_tx_expense': 'Pengeluaran',
      'recurring_tx_day': 'Tanggal',
      'recurring_tx_saved': 'Template transaksi rutin tersimpan',
      'recurring_tx_deleted': 'Template transaksi rutin dihapus',
      'recurring_tx_created_now':
          'Template tersimpan dan transaksi langsung dibuat.',
      'recurring_tx_scheduled':
          'Template tersimpan, akan berjalan otomatis sesuai tanggal.',
      'manage_recurring_transactions': 'Kelola Transaksi Berulang',
      'manage_recurring_transactions_desc': 'Atur transaksi otomatis bulanan',
      'recurring_name': 'Nama Template',
      'day_of_month': 'Tanggal',
      'savings_goal': 'Target Tabungan',
      'savings_progress': 'Progres Tabungan',
      'undo': 'Urungkan',
      'transaction_deleted': 'Transaksi dihapus',
      'transaction_restored': 'Transaksi dipulihkan',
      'category_budget': 'Anggaran Kategori',
      'set_budget': 'Atur Anggaran',
      'budget_per_category': 'Anggaran per Kategori',
      'no_budget_set': 'Belum diatur',
      'over_budget': 'Melebihi anggaran',
      'budget_remaining': 'Sisa anggaran',
      'transfer': 'Transfer',
      'transfer_between_wallets': 'Transfer Antar Dompet',
      'source_wallet': 'Dompet Asal',
      'destination_wallet': 'Dompet Tujuan',
      'transfer_success': 'Transfer berhasil disimpan',
      'same_wallet_error': 'Dompet asal dan tujuan tidak boleh sama',
      'category_transfer_out': 'Transfer Keluar',
      'category_transfer_in': 'Transfer Masuk',
      'ai_assistant': 'Asisten AI',
      'ai_insights': 'Insight Pintar',
      'ask_ai_hint': 'Tanya tentang keuanganmu...',
      'ai_key_required': 'Atur API key terlebih dahulu',
      'clear_chat': 'Hapus Riwayat Chat',
      'ai_powered_by': 'Ditenagai oleh Gemini AI',
      'ai_settings': 'Pengaturan AI',
      'edit_transaction': 'Edit Transaksi',
      'wallet_field': 'Dompet',
      'note_field': 'Catatan',
      'save_changes': 'Simpan Perubahan',
      'expense_amount': 'Nominal Pengeluaran',
      'income_amount': 'Nominal Pemasukan',
      'attachment_local': 'Lokal',
      'attachment_empty': 'Kosong',
      'change_btn': 'Ubah',
      'max_amount_error': 'Nominal terlalu besar (maksimal 1.000.000.000).',
      'wallet_category_required': 'Dompet dan kategori wajib dipilih.',
      'note_max_140': 'Catatan maksimal 140 karakter.',
      'invalid_tx_date': 'Tanggal transaksi tidak valid.',
      'failed_to_save': 'Gagal menyimpan',
      'action_pay': 'Bayar',
      'action_add_more': 'Tambah Lagi',
      'transaction_updated_success': 'Transaksi berhasil diperbarui.',
      'expense_saved_success': 'Pengeluaran berhasil disimpan.',
      'income_saved_success': 'Pemasukan berhasil disimpan.',
      'safe_to_spend_today': 'Aman belanja hari ini',
      'forecast_projection': 'Proyeksi akhir siklus',
      'forecast_days_left': 'Sisa hari',
      'forecast_upcoming_bills': 'Tagihan mendatang',
      'net_worth': 'Kekayaan Bersih',
      'cashflow_report': 'Arus Kas Bulanan',
      'closing_balance': 'Saldo Akhir',
      'assets_minus_liabilities': 'Aset dikurangi kewajiban',
      'debts': 'Utang & Piutang',
      'debts_desc': 'Catat pinjaman dan cicilan',
      'receivable': 'Piutang',
      'payable': 'Utang',
      'add_debt': 'Tambah Utang/Piutang',
      'debt_name': 'Nama Pihak',
      'debt_remaining': 'Sisa',
      'debt_settle': 'Bayar',
      'debt_settled': 'Lunas',
      'debt_due': 'Jatuh Tempo',
      'debt_no_due': 'Tanpa jatuh tempo',
      'debt_payment_amount': 'Jumlah Pembayaran',
      'import_csv': 'Import Mutasi (CSV)',
      'import_csv_desc': 'Tempel data mutasi bank untuk dicatat otomatis',
      'import_parse': 'Proses',
      'import_action': 'Import',
      'import_rows_found': 'transaksi terdeteksi',
      'import_none': 'Tidak ada baris valid terdeteksi',
      'import_hint':
          'Tempel CSV dengan kolom tanggal, keterangan, nominal. '
          'Contoh:\n16/09/2026; Indomaret; -125000\n17/09/2026; Gaji; 8000000',
      'import_success': 'Import selesai',
      'split_transaction': 'Transaksi Terbagi',
      'split_add_part': 'Tambah Kategori',
      'split_min_parts': 'Minimal 2 kategori dengan nominal di atas 0',
      'split_saved': 'Transaksi terbagi tersimpan',
      'debt_plan': 'Strategi Pelunasan',
      'debt_snowball': 'Snowball (saldo terkecil)',
      'debt_avalanche': 'Avalanche (bunga tertinggi)',
      'debt_monthly_payment': 'Dana cicilan / bulan',
      'debt_months_to_free': 'Lunas dalam (bulan)',
      'debt_interest_total': 'Total bunga',
      'debt_interest_rate': 'Bunga / tahun (%)',
      'debt_not_feasible': 'Dana bulanan belum cukup untuk melunasi',
      'sync_now': 'Sync sekarang',
      'create_now': 'Buat sekarang',
      'data_already_exists': 'Data sudah ada',
      'name_length_2_30': 'Panjang nama harus 2-30 karakter',
      'manual_tx_created': 'Transaksi manual berhasil dibuat dari template.',
      'export_success': 'Export berhasil',
      'delete_failed': 'Gagal menghapus',
      'save_failed': 'Gagal menyimpan',
      'budget_scope_required': 'Pilih dompet atau kategori untuk cakupan anggaran',
      'budget_limit_invalid': 'Limit anggaran tidak valid',
      },
    'en': {
      'profile': 'Profile',
      'app_preferences': 'App Preferences',
      'language': 'Language',
      'theme': 'Theme',
      'currency': 'Currency',
      'billing_cycle_start': 'Billing Cycle Start',
      'tx_time_input': 'Date Input',
      'tx_time_with_time': 'Date + Time',
      'tx_time_date_only': 'Date only',
      'date_label': 'Date',
      'notifications': 'Notifications',
      'recurring_bills': 'Recurring Bills',
      'recurring_bills_desc':
          'Bill reminders only, does not create transactions',
      'getting_started_title': 'Get Started',
      'getting_started_desc':
          'Add your first transaction and recurring bill to populate the dashboard.',
      'add_first_transaction': 'Add Transaction',
      'add_first_bill': 'Add Bill',
      'onboarding_step_tx': 'Add first transaction',
      'onboarding_step_bill': 'Add first recurring bill',
      'onboarding_step_streak': 'Record for 3 consecutive days',
      'habit_loop_title': 'Daily Consistency',
      'weekly_challenge': 'Weekly Challenge',
      'challenge_complete': 'Challenge completed. Keep the rhythm!',
      'challenge_progress_hint': 'Keep recording today to level up.',
      'day_short': 'day',
      'budget_limit': 'Budget Limit',
      'budget_limit_desc': 'Alert when nearing budget',
      'budget_settings': 'Budget Settings',
      'daily_summary': 'Daily Summary',
      'daily_summary_desc': 'Daily cashflow report',
      'summary_time': 'Summary Time',
      'security_sync': 'Security & Sync',
      'security_backup': 'Security & Backup',
      'backup_restore': 'Backup & Restore',
      'backup_restore_desc': 'Manage backup and restore data',
      'security_pin': 'Security PIN',
      'security_pin_desc': 'Fallback when biometrics fail',
      'create_pin': 'Create PIN',
      'change_pin': 'Change PIN',
      'confirm_pin': 'Confirm PIN',
      'pin_4_6_digits': 'Use 4-6 numeric digits',
      'remove_pin': 'Remove PIN',
      'remove_pin_desc': 'Disable PIN fallback',
      'pin_saved': 'Security PIN saved',
      'pin_removed': 'Security PIN removed',
      'pin_not_match': 'PIN and confirmation do not match',
      'backup_status_title': 'Backup Status',
      'backup_last': 'Last backup',
      'backup_never': 'No backup yet',
      'backup_now': 'Backup now',
      'data_reports': 'Data & Reports',
      'period': 'Period',
      'all_time': 'All time',
      'legal_privacy': 'Legal & Privacy',
      'legal_privacy_desc': 'Privacy policy, terms, data safety',
      'help': 'Help',
      'logout': 'Close Profile',
      'home_greeting': 'Hi',
      'financial_dashboard': 'Financial Dashboard',
      'total_balance': 'Net Balance',
      'income_this_cycle': 'Income',
      'expense_this_cycle': 'Expense',
      'monthly_bills': 'Monthly Bills',
      'item_count': 'items',
      'no_bills': 'No recurring bills yet',
      'due_today': 'Today',
      'due_in_days': 'days left',
      'due_date': 'Due on',
      'more_bills': 'more bills',
      'financial_analytics': 'Financial Analytics',
      'days_30': '30 Days',
      'saving_rate': 'Saving Rate',
      'burn_rate': 'Burn Rate',
      'runway': 'Runway',
      'trend_7_days': '7-Day Trend',
      'top_categories': 'Top Categories',
      'culinary_up': 'Dining up 24%',
      'wallet_title': 'My Wallet',
      'active_balance': 'Active Balance',
      'monthly_cashflow': 'Monthly Cashflow',
      'income': 'Income',
      'expense': 'Expense',
      'difference': 'Difference',
      'income_expense_history': 'Income/Expense History',
      'finance_analytics': 'Financial Analytics',
      'share_soon': 'Sharing reports coming soon',
      'this_week': 'This Week',
      'this_month': 'This Month',
      'this_year': 'This Year',
      'custom': 'Custom',
      'total_expense': 'Total Expense',
      'total_income': 'Total Income',
      'net_balance': 'Net Balance',
      'avg_daily': 'Average / Day',
      'expense_trend': 'EXPENSE TREND',
      'expense_composition': 'EXPENSE COMPOSITION',
      'out': 'Out',
      'in': 'In',
      'days_7': '7 Days',
      'largest_category': 'Largest category: Food & Drink (45%).',
      'transaction_detail': 'Transaction Detail',
      'history_soon': 'Transaction history will appear in the next update',
      'expense_tab': 'Expense',
      'income_tab': 'Income',
      'detail_info': 'DETAIL INFORMATION',
      'fund_source': 'Funding Source',
      'category': 'Category',
      'date_time': 'Date & Time',
      'add_note': 'Add a note...',
      'payment_proof': 'Receipt',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'cleared': 'Cleared',
      'add_recurring_bill': 'Add Recurring Bill',
      'save_data': 'SAVE DATA',
      'invalid_amount': 'Transaction amount is invalid',
      'saved_success': 'Transaction saved successfully',
      'monthly_recurring_bill': 'Monthly Recurring Bill',
      'bill_name': 'Bill Name',
      'bill_name_hint': 'Example: Water Bill',
      'amount': 'Amount',
      'amount_hint': 'Example: 250000',
      'due_day': 'Due Day',
      'due_day_hint': '1 - 31',
      'cancel': 'Cancel',
      'save': 'Save',
      'bill_added': 'Recurring bill added to dashboard',
      'bill_updated': 'Recurring bill updated',
      'bill_deleted': 'Recurring bill deleted',
      'edit': 'Edit',
      'delete': 'Delete',
      'manage_recurring_bills': 'Manage Recurring Bills',
      'manage_recurring_bills_desc':
          'Monthly bill reminders, not automatic transactions',
      'edit_recurring_bill': 'Edit Recurring Bill',
      'delete_recurring_bill': 'Delete Recurring Bill',
      'delete_recurring_bill_confirm': 'Are you sure you want to delete',
      'invalid_recurring_bill': 'Recurring bill data is invalid',
      'remove_seed_bills': 'Remove Sample Data',
      'seed_bills_removed': 'Sample recurring bills removed',
      'seed_bills_not_found': 'No sample data found',
      'master_data_center': 'Master Data Center',
      'master_data_center_desc': 'Manage wallets and categories',
      'manage_wallets': 'Manage Wallets',
      'manage_wallets_desc': 'Add or remove wallets',
      'rename_wallet': 'Rename Wallet',
      'rename_category': 'Rename Category',
      'wallet_name_hint': 'Example: savings_bri',
      'category_name_hint': 'Example: freelance',
      'add': 'Add',
      'budget_scope': 'Budget Scope',
      'budget_scope_all': 'All Spending',
      'budget_scope_category': 'By Category',
      'budget_scope_wallet': 'By Wallet',
      'budget_period_days': 'Period',
      'budget_calendar_month': 'Budget period: current calendar month',
      'select_language': 'Select Language',
      'select_theme': 'Select Theme',
      'select_currency': 'Select Currency',
      'theme_system': 'System',
      'theme_light': 'Light',
      'theme_dark': 'Dark',
      'recurring_bills_on': 'Recurring Bills Enabled',
      'recurring_bills_on_desc': 'Recurring bill reminders are now active.',
      'budget_on': 'Budget Alerts Enabled',
      'budget_on_desc': 'Budget notifications are now active.',
      'budget_alert': 'Alert',
      'daily_summary_body': 'Record your income and expenses today.',
      'daily_summary_on': 'Daily Summary Enabled',
      'daily_summary_on_desc': 'Daily summary notifications are now active.',
      'budget_saved': 'Budget Saved',
      'monthly_limit': 'Monthly Limit',
      'alert_when': 'Alert When',
      'alert_70': '70% of limit',
      'alert_80': '80% of limit',
      'alert_90': '90% of limit',
      'alert_100': '100% of limit',
      'transactions': 'Transactions',
      'categories': 'Categories',
      'accounts': 'Accounts',
      'export_reports': 'Export Reports',
      'export_reports_desc': 'Full CSV / summary PDF',
      'export_reports_action': 'Export started',
      'manage_categories': 'Manage Categories',
      'manage_categories_desc':
          'Categories are separated for income and expense',
      'manage_expense_categories': 'Expense Categories',
      'manage_expense_categories_desc':
          'Shown when the transaction type is expense',
      'manage_income_categories': 'Income Categories',
      'manage_income_categories_desc':
          'Shown when the transaction type is income',
      'expense_category_scope': 'This category is only for expenses',
      'income_category_scope': 'This category is only for income',
      'opening_balance': 'Opening Balance',
      'opening_balance_desc':
          'Wallet balance before you started recording transactions.',
      'sample_data': 'Sample',
      'sample_data_desc':
          'Sample data, safe to remove once real data is ready.',
      'manage_categories_action': 'Category manager opened',
      'manual_sync': 'Manual Sync',
      'manual_sync_desc': 'Last: today 14:03',
      'manual_sync_action': 'Manual sync started',
      'help_center': 'Help Center',
      'help_center_desc': 'Guides & FAQ',
      'help_center_action': 'Help center opened',
      'contact_support': 'Contact Support',
      'contact_support_desc': 'Reply < 24 hours',
      'contact_support_action': 'Support form opened',
      'about_app': 'About App',
      'about_app_desc': 'Version 1.0.0+1',
      'about_app_action': 'App info opened',
      'biometric_lock': 'Biometric Lock',
      'biometric_lock_desc': 'Unlock with fingerprint/face',
      'cloud_sync': 'Cloud Sync',
      'cloud_sync_desc': 'Not active yet. Use local backup to move devices',
      'auto_backup': 'Auto Backup',
      'auto_backup_desc': 'Weekly encrypted local backup, not cloud sync',
      'per_day': 'day',
      'runway_value': '5.9 mo',
      'category_food': 'Dining',
      'category_transport': 'Transport',
      'category_bills': 'Bills',
      'category_food_drink': 'Food & Drink',
      'category_monthly_shopping': 'Monthly Shopping',
      'category_shopping': 'Shopping',
      'category_entertainment': 'Entertainment',
      'category_health': 'Health',
      'category_education': 'Education',
      'category_others': 'Others',
      'category_salary': 'Salary',
      'category_freelance': 'Freelance',
      'category_bonus': 'Bonus',
      'category_business': 'Business',
      'category_investment': 'Investment',
      'category_gift': 'Gift',
      'wallet_cash': 'Cash',
      'wallet_bank': 'Bank',
      'wallet_ewallet': 'E-Wallet',
      'wallet_card': 'Card',
      'salary_in': 'Salary Income',
      'company_to_bank': 'Company -> BCA',
      'pay_water': 'Water Bill (PDAM)',
      'monthly_shopping': 'Monthly Shopping',
      'credit_card': 'Credit Card',
      'cash': 'Cash',
      'date_mar_1_2026': 'Mar 1, 2026',
      'date_mar_5_2026': 'Mar 5, 2026',
      'date_mar_7_2026': 'Mar 7, 2026',
      'trx_52': '52 tx',
      'trx_18': '18 tx',
      'trx_14': '14 tx',
      'trx_7': '7 tx',
      'logout_action': 'Sign out process prepared',
      'no_data': 'No data yet',
      'transactions_count': 'transactions',
      'see_all_breakdown': 'See All Categories',
      'expense_by_category': 'Expense by Category',
      'total': 'Total',
      'largest_category_none': 'No dominant category yet',
      'month_short': 'mo',
      'top_categories_info':
          'Top 3 categories with highest spending in the current cycle.',
      'no_tx_short': '0',
      'saving_rate_info':
          'Percentage of income saved after subtracting spending in the current cycle.',
      'burn_rate_info':
          'Average daily spending in the current cycle. Higher means cash is used up faster.',
      'runway_info':
          'Estimated time your current balance can last if spending pattern stays the same.',
      'saving_rate_example':
          'Example: Income 5M, spending 3M, saving rate = 40%',
      'burn_rate_example': 'Example: Spending 3M over 30 days = 100K/day',
      'runway_example':
          'Example: Balance 10M, burn rate 100K/day = about 100 days',
      'search_hint': 'Search transactions...',
      'search_empty': 'No transactions found',
      'notif_center_title': 'Notification Center',
      'notif_center_empty': 'No notifications yet',
      'notif_bill_due_title': 'Bill due soon',
      'notif_upcoming': 'Soon',
      'notif_expense_added': 'Expense recorded',
      'notif_income_added': 'Income recorded',
      'notif_just_now': 'Just now',
      'monthly_close_title': 'Monthly Close',
      'monthly_close_export_pdf': 'Export PDF',
      'monthly_close_exported': 'PDF saved at',
      'recent_activity_title': 'Recent Activity',
      'tap_to_edit': 'Tap to edit',
      'savings_goal_title': 'Savings Goal',
      'set_goal': 'Set',
      'savings_goal_empty': 'No savings goal yet',
      'goal_reached': 'Goal reached',
      'goal_progress': '{value}% reached',
      'goal_name': 'Goal Name',
      'goal_target_amount': 'Target Amount',
      'delete_goal': 'Delete Goal',
      'export_failed': 'Export failed',
      'recurring_tx_title': 'Automatic Transaction Templates',
      'recurring_tx_manage': 'Transaction templates',
      'recurring_tx_add': 'Add Template',
      'recurring_tx_edit': 'Edit Template',
      'recurring_tx_empty': 'No recurring transaction template yet',
      'recurring_tx_type': 'Type',
      'recurring_tx_income': 'Income',
      'recurring_tx_expense': 'Expense',
      'recurring_tx_day': 'Date',
      'recurring_tx_saved': 'Recurring template saved',
      'recurring_tx_deleted': 'Recurring template deleted',
      'recurring_tx_created_now':
          'Template saved and a transaction was created right away.',
      'recurring_tx_scheduled':
          'Template saved, it will run automatically on schedule.',
      'manage_recurring_transactions': 'Manage Recurring Transactions',
      'manage_recurring_transactions_desc': 'Manage monthly auto-transactions',
      'recurring_name': 'Template Name',
      'day_of_month': 'Day of Month',
      'savings_goal': 'Savings Goal',
      'savings_progress': 'Savings Progress',
      'undo': 'Undo',
      'transaction_deleted': 'Transaction deleted',
      'transaction_restored': 'Transaction restored',
      'category_budget': 'Category Budget',
      'set_budget': 'Set Budget',
      'budget_per_category': 'Budget per Category',
      'no_budget_set': 'Not set',
      'over_budget': 'Over budget',
      'budget_remaining': 'Budget remaining',
      'transfer': 'Transfer',
      'transfer_between_wallets': 'Transfer Between Wallets',
      'source_wallet': 'Source Wallet',
      'destination_wallet': 'Destination Wallet',
      'transfer_success': 'Transfer saved successfully',
      'same_wallet_error': 'Source and destination wallet must be different',
      'category_transfer_out': 'Transfer Out',
      'category_transfer_in': 'Transfer In',
      'ai_assistant': 'AI Assistant',
      'ai_insights': 'Smart Insights',
      'ask_ai_hint': 'Ask about your finances...',
      'ai_key_required': 'Set API key first',
      'clear_chat': 'Clear Chat History',
      'ai_powered_by': 'Powered by Gemini AI',
      'ai_settings': 'AI Settings',
      'edit_transaction': 'Edit Transaction',
      'wallet_field': 'Wallet',
      'note_field': 'Note',
      'save_changes': 'Save Changes',
      'expense_amount': 'Expense Amount',
      'income_amount': 'Income Amount',
      'attachment_local': 'Local',
      'attachment_empty': 'Empty',
      'change_btn': 'Change',
      'max_amount_error': 'Amount too large (max 1,000,000,000).',
      'wallet_category_required': 'Wallet and category are required.',
      'note_max_140': 'Note max 140 characters.',
      'invalid_tx_date': 'Invalid transaction date.',
      'failed_to_save': 'Failed to save',
      'action_pay': 'Pay',
      'action_add_more': 'Add More',
      'transaction_updated_success': 'Transaction updated successfully.',
      'expense_saved_success': 'Expense saved successfully.',
      'income_saved_success': 'Income saved successfully.',
      'safe_to_spend_today': 'Safe to spend today',
      'forecast_projection': 'Projected cycle end',
      'forecast_days_left': 'Days left',
      'forecast_upcoming_bills': 'Upcoming bills',
      'net_worth': 'Net Worth',
      'cashflow_report': 'Monthly Cash Flow',
      'closing_balance': 'Closing balance',
      'assets_minus_liabilities': 'Assets minus liabilities',
      'debts': 'Debts & Receivables',
      'debts_desc': 'Track loans and installments',
      'receivable': 'Receivable',
      'payable': 'Payable',
      'add_debt': 'Add Debt/Receivable',
      'debt_name': 'Counterparty',
      'debt_remaining': 'Remaining',
      'debt_settle': 'Pay',
      'debt_settled': 'Settled',
      'debt_due': 'Due date',
      'debt_no_due': 'No due date',
      'debt_payment_amount': 'Payment amount',
      'import_csv': 'Import Statement (CSV)',
      'import_csv_desc': 'Paste bank statement rows to record automatically',
      'import_parse': 'Parse',
      'import_action': 'Import',
      'import_rows_found': 'transactions detected',
      'import_none': 'No valid rows detected',
      'import_hint':
          'Paste CSV with date, description, amount columns. '
          'Example:\n16/09/2026; Indomaret; -125000\n17/09/2026; Salary; 8000000',
      'import_success': 'Import finished',
      'split_transaction': 'Split Transaction',
      'split_add_part': 'Add Category',
      'split_min_parts': 'At least 2 categories with amounts above 0',
      'split_saved': 'Split transaction saved',
      'debt_plan': 'Payoff Strategy',
      'debt_snowball': 'Snowball (smallest balance)',
      'debt_avalanche': 'Avalanche (highest interest)',
      'debt_monthly_payment': 'Monthly payment budget',
      'debt_months_to_free': 'Debt-free in (months)',
      'debt_interest_total': 'Total interest',
      'debt_interest_rate': 'Interest / year (%)',
      'debt_not_feasible': 'Monthly budget is not enough to clear the debt',
      'sync_now': 'Sync now',
      'create_now': 'Create now',
      'data_already_exists': 'Data already exists',
      'name_length_2_30': 'Name must be 2-30 characters',
      'manual_tx_created': 'Manual transaction created from template.',
      'export_success': 'Export succeeded',
      'delete_failed': 'Failed to delete',
      'save_failed': 'Failed to save',
      'budget_scope_required': 'Choose a wallet or category for the budget scope',
      'budget_limit_invalid': 'Budget limit is invalid',
    },
  };

  String t(String key) {
    return _values[locale.languageCode]?[key] ?? _values['en']?[key] ?? key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['id', 'en'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
