name: Flutter CI

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  quality-gate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter Version
        run: flutter --version

      - name: Get Dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze lib test

      - name: Run Tests
        run: flutter test

      - name: Build APK (Debug)
        run: flutter build apk --debug
